spring.application.name=order-inventory-service
# Server
server.port=8080

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5433/order_inventory
spring.datasource.username=app
spring.datasource.password=app

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.clean-disabled=false

#security
spring.security.user.name=user
spring.security.user.password=pass123
